import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookieToInitialState } from 'wagmi'
import { headers } from 'next/headers'
import { config } from '@/app/config'
import Web3ModalProvider from '@/app/context'
import { Toaster } from "react-hot-toast";

export const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <Web3ModalProvider initialState={initialState}>{children}</Web3ModalProvider>
      </body>
    </html>
  );
}